// <auto-generated />
using Backwords.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backwords.Api.Migrations
{
    [DbContext(typeof(BackwordsDbContext))]
    [Migration("20260917173334_RenameLanguageColumn")]
    partial class RenameLanguageColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Backwords.Api.Models.Derivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedTermId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TermId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelatedTermId");

                    b.HasIndex("TermId");

                    b.ToTable("Derivations");
                });

            modelBuilder.Entity("Backwords.Api.Models.Lexeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeedWord")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lexemes");
                });

            modelBuilder.Entity("Backwords.Api.Models.Derivation", b =>
                {
                    b.HasOne("Backwords.Api.Models.Lexeme", "RelatedTerm")
                        .WithMany()
                        .HasForeignKey("RelatedTermId");

                    b.HasOne("Backwords.Api.Models.Lexeme", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedTerm");

                    b.Navigation("Term");
                });
#pragma warning restore 612, 618
        }
    }
}
