namespace Backwords.Api;

using System.Collections.Generic;

/// <summary>
/// Curated starting word list for the etymology import pipeline. Each entry is an
/// English headword to seed a lineage chain from (see seed-words.md for the
/// original draft/rationale, and DESIGN.md for the "is_seed_word" concept).
///
/// Deduplicated from seed-words.md; words that seem unlikely to have a rich
/// etymology-db entry (e.g. very modern compounds like "open-source") are kept
/// in for now — prune during import once you see which ones actually resolve
/// to real chains, per seed-words.md's own note.
/// </summary>
public static class SeedWords
{
    public const string English = "English";
    public static readonly List<(string Term, string Language)> All =
    [
        // Greatest hits
        ("robot", English),
        ("algorithm", English),
        ("computer", English),
        ("bug", English),
        ("virus", English),
        ("spam", English),
        ("cursor", English),
        ("avatar", English),
        ("cloud", English),
        ("byte", English),
        // Core computing / software vocabulary
        ("software", English),
        ("hardware", English),
        ("program", English),
        ("compile", English),
        ("debug", English),
        ("execute", English),
        ("kernel", English),
        ("cache", English),
        ("buffer", English),
        ("protocol", English),
        ("syntax", English),
        ("semantics", English),
        ("compiler", English),
        ("interpreter", English),
        ("runtime", English),
        ("process", English),
        ("thread", English),
        ("stack", English),
        ("queue", English),
        ("heap", English),
        ("pointer", English),
        ("array", English),
        ("string", English),
        ("integer", English),
        ("boolean", English),
        ("variable", English),
        ("function", English),
        ("method", English),
        ("class", English),
        ("object", English),
        ("interface", English),
        ("module", English),
        ("library", English),
        ("framework", English),
        ("repository", English),
        ("commit", English),
        ("branch", English),
        ("merge", English),
        ("deploy", English),
        ("server", English),
        ("client", English),
        ("database", English),
        ("query", English),
        ("index", English),
        ("schema", English),
        ("network", English),
        ("packet", English),
        ("socket", English),
        ("firewall", English),
        ("encryption", English),
        ("key", English),
        ("token", English),
        ("session", English),
        ("cookie", English),
        ("latency", English),
        ("bandwidth", English),
        ("router", English),
        ("gateway", English),
        ("node", English),
        ("cluster", English),
        ("container", English),
        ("pipeline", English),
        ("automation", English),
        ("script", English),
        ("terminal", English),
        ("shell", English),
        ("console", English),
        ("log", English),
        ("debugger", English),
        ("breakpoint", English),
        ("exception", English),
        ("error", English),
        ("warning", English),
        ("patch", English),
        ("update", English),
        ("version", English),
        ("release", English),
        ("build", English),
        ("test", English),
        ("mock", English),
        ("stub", English),
        ("refactor", English),
        ("legacy", English),
        ("deprecated", English),
        ("license", English),
        // Broader tech / digital vocabulary
        ("internet", English),
        ("web", English),
        ("browser", English),
        ("hyperlink", English),
        ("domain", English),
        ("url", English),
        ("email", English),
        ("download", English),
        ("upload", English),
        ("stream", English),
        ("format", English),
        ("encode", English),
        ("decode", English),
        ("compress", English),
        ("archive", English),
        ("backup", English),
        ("restore", English),
        ("sync", English),
        ("digital", English),
        ("analog", English),
        ("binary", English),
        ("hexadecimal", English),
        ("bit", English),
        ("pixel", English),
        ("resolution", English),
        ("render", English),
        ("graphic", English),
        ("widget", English),
        ("dashboard", English),
        ("notification", English),
        ("keyboard", English),
        ("mouse", English),
        ("monitor", English),
        ("printer", English),
        ("scanner", English),
        ("modem", English),
        ("firmware", English),
        ("driver", English),
        ("plugin", English),
        ("extension", English),
        ("sandbox", English),
        ("emulator", English),
        ("simulator", English),
        ("virtual", English),
        ("persona", English),
        ("username", English),
        ("password", English),
        ("login", English),
        ("logout", English),
        ("phishing", English),
        ("malware", English),
        ("worm", English),
        ("trojan", English),
        ("antivirus", English),
        ("exploit", English),
        ("vulnerability", English),
        ("breach", English),
    ];
}
